### ISSUE TITLE
Fix nutshell style errors.

### ISSUE THREAD

**Issue by JojokCreator** [jfrome1/NTW2029#12]
fix Nutshell links line break--links with text in them have a line break after the first word (see :formatting guidelines link on [guidelines.md](http://guidelines.md/))
✅remove space between Nutshell bulleted lists
✅ fix button spacing for close button at bottom of Nutshells (currently it's too short, so hard to click links on last line of bubble text)
✅ fix text wrap for table cells and for code blocks in Nutshells

## Fix;
Inside ./src/styles/custom.css adjust these lines

For space between bullets
```css
.nutshell-bubble li {
	margin-bottom: 0.1em;
}
```

For space between close button
```css
.nutshell-bubble-overflow-section {
	margin-bottom: 1em; ///Add this
}
```

For table fix
```css
table {
	max-width: 560px;
	white-space: normal;
}
```

To add letters to ordered lists
```css
ol ol {
	list-style-type: lower-alpha;
}
}
```
