### ISSUE TITLE
To adjust styling on the feedback component.

### ISSUE THREAD

**Issue by JojokCreator** [jfrome1/NTW2029#13]
To fix the styles on the feedback message form.
![image](https://github.com/user-attachments/assets/31c8ef31-30a2-4d5d-bd8c-266e59d7821b)

Go to the FeedbackAnalyticsComponent.astro component 

Change the style below.

```css
        .feelback-container {
        margin: 2rem auto 3rem;
        --max-width: 400px !important;
    }
```

The auto part is the left and right margins. If you give auto they take up all the space. Set it to 0 and it should make the component fill all the space. Or use a fixed margin 0.5rem

Probably remove the max width too.
