### ISSUE TITLE
Fix styling issues with nutshell dropdowns.

### ISSUE THREAD

**Issue by JojokCreator** [jfrome1/NTW2029#14]
Code blocks.
![image](https://github.com/user-attachments/assets/32355320-f6bc-4451-aa0f-7459d979e2f3)

Fix 
```css
.nutshell-bubble code {
	background: #ddd;   <--- Remove this
	border-radius: 5px;
	/*font-weight:100;*/
	padding: 0 5px;
}
```

**Comment by JojokCreator** [comment]
add this 
```css
.nutshell-bubble code {
	background: var(--sl-color-accent-low);
	color: var(--sl-color-white);
	border-radius: 5px;
	/*font-weight:100;*/
	padding: 0 5px;
}
```

**Comment by JojokCreator** [comment]
When you add colors use the variables from here. As the will then switch in Dark Mode.

```css
/* Dark mode colors. */
:root {
	--sl-color-accent-low: #131e4f;
	--sl-color-accent: #3447ff;
	--sl-color-accent-high: #b3c7ff;
	--sl-color-white: #ffffff;
	--sl-color-gray-1: #eceef2;
	--sl-color-gray-2: #c0c2c7;
	--sl-color-gray-3: #888b96;
	--sl-color-gray-4: #545861;
	--sl-color-gray-5: #353841;
	--sl-color-gray-6: #24272f;
	--sl-color-black: #17181c;
}

/* Light mode colors. */
:root[data-theme='light'] {
	--sl-color-accent-low: #c7d6ff;
	--sl-color-accent: #364bff;
	--sl-color-accent-high: #182775;
	--sl-color-white: #17181c;
	--sl-color-gray-1: #24272f;
	--sl-color-gray-2: #353841;
	--sl-color-gray-3: #545861;
	--sl-color-gray-4: #888b96;
	--sl-color-gray-5: #c0c2c7;
	--sl-color-gray-6: #eceef2;
	--sl-color-gray-7: #f5f6f8;
	--sl-color-black: #ffffff;
}
```

**Comment by JojokCreator** [comment]
![image](https://github.com/user-attachments/assets/4593987d-fded-4115-9e6a-87d84242afe7)

Another on /course-ntw2029/schedule#x-videos

```css 
.nutshell-bubble {

	/* Gon' stretch out */
	display: inline-block;
	width: 100%;
	background-color: var(--sl-color-black) !important; < ---- Add
	color: var(--sl-color-white) !important; < ---- Add
}
	
```
