### ISSUE TITLE
Followups too light

### ISSUE THREAD

**Issue by JojokCreator** [jfrome1/NTW2029#15]
![image](https://github.com/user-attachments/assets/c6a15ddd-8d76-4c40-a1d4-a13fa304b1c9)

```css
.nutshell-followup {
	opacity: 0.33; < ---- change this to 1
}
```
